name: your_psychiatrist
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for ios style icons.
  cupertino_icons: ^1.0.2
  # State management
  flutter_bloc: ^8.1.4
  # Code generator ( mainly used with cubit & retrofit )
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  # For dependency injection
  get_it: ^7.6.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  # Localization
  intl: ^0.18.1
  easy_localization: ^3.0.5
  # For splash screen
  flutter_native_splash: ^2.3.13
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # A flutter plugin for adapting screen and font size.(responsive)
  flutter_screenutil: ^5.9.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg






  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #